# permissions for end users to view emergencyaccounts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: emergencyaccount-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: emergency-credentials-controller
    app.kubernetes.io/part-of: emergency-credentials-controller
    app.kubernetes.io/managed-by: kustomize
  name: emergencyaccount-viewer-role
rules:
- apiGroups:
  - cluster.appuio.io
  resources:
  - emergencyaccounts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cluster.appuio.io
  resources:
  - emergencyaccounts/status
  verbs:
  - get
